# Generated by Django 5.1 on 2024-08-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('karyawan', 'Karyawan'), ('calon_karyawan', 'Calon_karyawan')], max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
