# Generated by Django 5.1 on 2024-08-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='calonKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIK', models.IntegerField()),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('JK', models.CharField(choices=[('laki_laki', 'Laki Laki'), ('perempuan', 'Perempuan')], default=None, max_length=10)),
                ('agama', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('kawin', 'Kawin'), ('belum_kawin', 'Belum Kawin')], default=None, max_length=50)),
                ('jumlah_anak', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('no_telephone', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images_profile/')),
                ('ktp', models.FileField(upload_to='')),
                ('ijazah', models.FileField(upload_to='')),
                ('status_wawancara', models.CharField(choices=[('diterima', 'Diterima'), ('tidak_diterima', 'Tidak Diterima')], default=None, max_length=20)),
                ('upload_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('karyawan', 'Karyawan'), ('calon_karyawan', 'Calon Karyawan')], default='calon_karyawan', max_length=50),
        ),
    ]
