# Generated by Django 5.1 on 2024-08-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_calonkaryawan_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='calonkaryawan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calon_karyawan', to='api.users'),
        ),
    ]
