# Generated by Django 5.1 on 2024-08-24 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_calonkaryawan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calonkaryawan',
            old_name='JK',
            new_name='jenis_kelamin',
        ),
        migrations.RenameField(
            model_name='calonkaryawan',
            old_name='NIK',
            new_name='nik',
        ),
    ]
