# Generated by Django 5.1 on 2024-09-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_jk_calonkaryawan_jenis_kelamin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_departement', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='calonkaryawan',
            name='ijazah',
            field=models.FileField(blank=True, null=True, upload_to='ijazah_pdf/'),
        ),
        migrations.AlterField(
            model_name='calonkaryawan',
            name='ktp',
            field=models.FileField(blank=True, null=True, upload_to='ktp_pdf/'),
        ),
    ]
