# Generated by Django 5.1 on 2024-09-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_departement_alter_calonkaryawan_ijazah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='periodePenggajian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('non_active', 'Non Active')], default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.IntegerField()),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('karyawan', 'Karyawan'), ('calon_karyawan', 'Calon Karyawan')], default='calon_karyawan', max_length=50)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('agama', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('jumlah_anak', models.IntegerField()),
                ('alamat', models.CharField(max_length=100)),
                ('no_telpon', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_karyawan/')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departement', to='api.departement')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawan', to='api.users')),
            ],
        ),
    ]
