# Generated by Django 5.1 on 2024-09-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_periodepenggajian_karyawan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='periodepenggajian',
            old_name='status',
            new_name='statusPeriode',
        ),
    ]
