# Generated by Django 5.1 on 2024-09-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_periodepenggajian_statusperiode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodepenggajian',
            name='statusPeriode',
        ),
        migrations.AddField(
            model_name='periodepenggajian',
            name='status_periode',
            field=models.CharField(choices=[('active', 'Active'), ('non_active', 'Non Active')], default='non_active', max_length=50),
        ),
    ]
