# Generated by Django 5.1 on 2024-09-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_periodepenggajian_statusperiode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodepenggajian',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
