# Generated by Django 5.1 on 2024-09-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_periodepenggajian_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='tunjanganKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tunjangan_makan', models.IntegerField()),
                ('tunjangan_kesehatan', models.IntegerField()),
                ('tunjangan_jabatan', models.IntegerField()),
                ('THR', models.IntegerField()),
                ('bonus', models.IntegerField()),
            ],
        ),
    ]
