# Generated by Django 5.1 on 2024-09-06 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_tunjangankaryawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinjamanKaryawan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_pinjaman', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_pinjaman', models.DateField()),
                ('tenggat_pinjam', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='calonkaryawan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calonkaryawan',
            name='jumlah_anak',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='departement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departement', to='api.departement'),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tunjangankaryawan',
            name='THR',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tunjangankaryawan',
            name='bonus',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tunjangankaryawan',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tunjangankaryawan',
            name='tunjangan_jabatan',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tunjangankaryawan',
            name='tunjangan_kesehatan',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='tunjangankaryawan',
            name='tunjangan_makan',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.CreateModel(
            name='LaporanPenggajian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_gaji', models.DateField()),
                ('gaji_mentah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pinjaman', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gaji_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jumlah_izin', models.IntegerField()),
                ('jumlah_sakit', models.IntegerField()),
                ('periodegaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporanpenggajian', to='api.periodepenggajian')),
                ('tunjangan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporanpenggajian', to='api.tunjangankaryawan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporanpenggajian', to='api.users')),
            ],
        ),
    ]
