# Generated by Django 5.1 on 2024-09-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_pinjamankaryawan_alter_calonkaryawan_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KehadiranKaryawan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('informasi_kehadiran', models.CharField(max_length=100)),
                ('jam_masuk', models.TimeField()),
                ('jam_pulang', models.TimeField()),
                ('total_jam_kerja', models.TimeField()),
                ('keterangan_kehadiran', models.CharField(choices=[('sakit', 'Sakit'), ('izin', 'izin'), ('alpha', 'Alpha')], default=None, max_length=50)),
                ('total_jam_lembur', models.TimeField()),
                ('biaya_pengobatan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kehadirankaryawan', to='api.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='SlipGaji',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('terima_dari', models.CharField(max_length=100)),
                ('nominal_gaji', models.DecimalField(decimal_places=2, max_digits=12)),
                ('untuk_pembayaran', models.CharField(max_length=100)),
                ('Laporan_penggajian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laporanpenggajian', to='api.laporanpenggajian')),
                ('karyawan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slipgaji', to='api.karyawan')),
            ],
        ),
    ]
