from .user_models import Users
from .calonkaryawan_models import CalonKaryawan
from .departement_models import Departement
from .periodGaji_models import periodePenggajian
from .karyawan_models import Karyawan
from .tunjangan_models import tunjanganKaryawan
from .pinjamankaryawan_models import PinjamanKaryawan
from .laporanpenggajian_models import LaporanPenggajian
from .kehadirankaryawan_models import KehadiranKaryawan
from .slipgaji_models import SlipGaji
from .transaksi_pembayaran_pinjaman import TransaksiPinjaman